language: node_js
node_js:
- '8'
- '10'
- '12'
services:
- redis-server
before_script:
- npm install -g codecov
script: npm run testci
deploy:
  provider: npm
  api_key:
    secure: QnQR0s6z6kwjLZIabAZfN/1f8OjDDNwb66QRvzCgQCQfxMw62ECnApyokuJYT1AX0/7S4PPYhkBHkCd1GSwaYwa4hQ+0k4TJh/W9niSNBwKR7CfJ0/yfvnYSR2x+uGVd2Ontpb9GeW9QDFC+Jq39p/u0CS+1dSCvezbUfoMHVG4=
  email:
    secure: ReldtI/qWiezDWylhENP+QWnyTlVOQgfdUoCmfZ+3yt70hdRMZeFF2Lwhp31Lzlf+8KmSlw1TGPTyTHqv1SE/artFuGr1+GuDp6bC17aBsSx9G5bc/QpQtL+xW4f+3/kS+Zubxa4D6ajxMa+lfR0qPAhBdso5vjXyypCmp4CaOU=
  on:
    tags: true
    repo: getconversio/redis-metrics
notifications:
  slack:
    secure: EBNkXvxS4CvMUzzLLDDraZlj0mpq/cQ809emxZKG/7Ld7j/E0SDqbngegFSTT1JsJpaIiyF/9eV9nkgqs8QYIz0QMajobKaSQI/u2UTxyWXuH6r99xJaWDIFIhl6mCxYh1dqfbEJUMAAIAsUW3HCxfZTNyp0NqEVu3+YXcvExjc=
